/* GENERATED by gen_abi_probe.py -- do not edit.
 * Struct bodies are lifted verbatim from gadget.c, so this
 * cannot drift from the driver.
 */
#include <stdio.h>
#include <stddef.h>
#include <stdint.h>
typedef uint8_t  u8;
typedef uint16_t __le16;
typedef uint32_t __le32;
typedef uint64_t __le64;

struct dwc2_r1_rec {
	__le32 seq;
	__le16 tag;
	__le16 flags;
	__le16 w_value;
	__le16 w_index;
	__le16 w_length;
	u8 bm_request_type;
	u8 b_request;
	u8 trigger;
	u8 ep_index;
	u8 causal_state;	/* enum dwc2_r1_cause */
	u8 mapping_class;	/* enum dwc2_r1_mapping */
	__le32 gintsts;
	__le32 dctl;
	__le32 doepctl;
	__le32 doepint;
	__le32 grstctl;
	__le32 gahbcfg;
	__le32 status;
	/* --- v6.3 --- */
	__le64 setup_cookie;
	__le64 req_dma;
	__le32 req_length;
	__le32 req_actual;
	__le16 num_sgs;
	__le16 num_mapped_sgs;
	__le16 flags2;
	__le16 owner_cpu;
};

struct dwc2_r1_dump_hdr {
	__le32 magic;
	__le32 version;
	__le32 header_size;
	__le32 record_size;
	__le32 count;
	__le32 lost;
	__le32 next_seq;
	__le32 caps_flags;
	__le32 gsnpsid;
	__le32 ghwcfg2;
	__le32 ghwcfg3;
	__le32 ghwcfg4;
	__le32 reset_generation;
	__le32 setup_cfg0_seen;
	__le32 setup_cfgn_seen;
	__le32 setup_intf_seen;
	__le32 candidate_cfg0_seen;
	__le32 candidate_cfgn_seen;
	__le32 candidate_intf_seen;
	__le32 candidate_delayed_seen;
	__le32 overlap_count;
	__le32 delayed_open_count;
	__le32 delayed_closed_count;
	__le32 causal_sync_count;
	__le32 causal_unattributed_count;
	/*
	 * 1 when the dump was taken under a single lock acquisition, so the
	 * counters above and the records below are from the same instant.
	 * v6.2 could not assert this: it read count, dropped the lock to
	 * allocate, then re-took it to fill the header and copy a prefix, so
	 * a header from T2 could accompany records from T1.
	 */
	__le32 snapshot_atomic;
	__le32 reserved0;
	__le32 reserved1;
};

#define F(s, f) printf("%-26s %3zu %3zu\n", #f, offsetof(struct s, f), sizeof(((struct s *)0)->f))

int main(void)
{
	printf("struct dwc2_r1_rec  size=%zu\n", sizeof(struct dwc2_r1_rec));
	printf("%-26s %3s %3s\n", "field", "off", "sz");
	F(dwc2_r1_rec, seq);
	F(dwc2_r1_rec, tag);
	F(dwc2_r1_rec, flags);
	F(dwc2_r1_rec, w_value);
	F(dwc2_r1_rec, w_index);
	F(dwc2_r1_rec, w_length);
	F(dwc2_r1_rec, bm_request_type);
	F(dwc2_r1_rec, b_request);
	F(dwc2_r1_rec, trigger);
	F(dwc2_r1_rec, ep_index);
	F(dwc2_r1_rec, causal_state);
	F(dwc2_r1_rec, mapping_class);
	F(dwc2_r1_rec, gintsts);
	F(dwc2_r1_rec, dctl);
	F(dwc2_r1_rec, doepctl);
	F(dwc2_r1_rec, doepint);
	F(dwc2_r1_rec, grstctl);
	F(dwc2_r1_rec, gahbcfg);
	F(dwc2_r1_rec, status);
	F(dwc2_r1_rec, setup_cookie);
	F(dwc2_r1_rec, req_dma);
	F(dwc2_r1_rec, req_length);
	F(dwc2_r1_rec, req_actual);
	F(dwc2_r1_rec, num_sgs);
	F(dwc2_r1_rec, num_mapped_sgs);
	F(dwc2_r1_rec, flags2);
	F(dwc2_r1_rec, owner_cpu);
	printf("\n");
	printf("struct dwc2_r1_dump_hdr  size=%zu\n", sizeof(struct dwc2_r1_dump_hdr));
	printf("%-26s %3s %3s\n", "field", "off", "sz");
	F(dwc2_r1_dump_hdr, magic);
	F(dwc2_r1_dump_hdr, version);
	F(dwc2_r1_dump_hdr, header_size);
	F(dwc2_r1_dump_hdr, record_size);
	F(dwc2_r1_dump_hdr, count);
	F(dwc2_r1_dump_hdr, lost);
	F(dwc2_r1_dump_hdr, next_seq);
	F(dwc2_r1_dump_hdr, caps_flags);
	F(dwc2_r1_dump_hdr, gsnpsid);
	F(dwc2_r1_dump_hdr, ghwcfg2);
	F(dwc2_r1_dump_hdr, ghwcfg3);
	F(dwc2_r1_dump_hdr, ghwcfg4);
	F(dwc2_r1_dump_hdr, reset_generation);
	F(dwc2_r1_dump_hdr, setup_cfg0_seen);
	F(dwc2_r1_dump_hdr, setup_cfgn_seen);
	F(dwc2_r1_dump_hdr, setup_intf_seen);
	F(dwc2_r1_dump_hdr, candidate_cfg0_seen);
	F(dwc2_r1_dump_hdr, candidate_cfgn_seen);
	F(dwc2_r1_dump_hdr, candidate_intf_seen);
	F(dwc2_r1_dump_hdr, candidate_delayed_seen);
	F(dwc2_r1_dump_hdr, overlap_count);
	F(dwc2_r1_dump_hdr, delayed_open_count);
	F(dwc2_r1_dump_hdr, delayed_closed_count);
	F(dwc2_r1_dump_hdr, causal_sync_count);
	F(dwc2_r1_dump_hdr, causal_unattributed_count);
	F(dwc2_r1_dump_hdr, snapshot_atomic);
	F(dwc2_r1_dump_hdr, reserved0);
	F(dwc2_r1_dump_hdr, reserved1);
	printf("\n");
	return 0;
}
