#!/usr/bin/env python3
"""Regenerate abi_probe.c from a patched gadget.c.

This is the script the "cannot drift from the driver" claim rests on, so it
ships with the bundle rather than living in someone's shell history. It lifts
the two struct bodies verbatim -- no transcription -- and emits a program that
prints their real layout.

  usage: gen_abi_probe.py path/to/drivers/usb/dwc2/gadget.c [-o abi_probe.c]
"""
import argparse
import re
import sys

TYPES = r'(?:u8|__le16|__le32|__le64)'


def grab(src, name):
    m = re.search(r'struct %s \{.*?\n\};' % re.escape(name), src, re.S)
    if not m:
        sys.exit('struct %s not found -- is this a patched gadget.c?' % name)
    return m.group(0)


def fields(body):
    return re.findall(r'^\s*%s\s+(\w+);' % TYPES, body, re.M)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('gadget')
    ap.add_argument('-o', '--out', default='abi_probe.c')
    a = ap.parse_args()

    src = open(a.gadget).read()
    rec = grab(src, 'dwc2_r1_rec')
    hdr = grab(src, 'dwc2_r1_dump_hdr')

    body = ['/* GENERATED by gen_abi_probe.py -- do not edit.',
            ' * Struct bodies are lifted verbatim from gadget.c, so this',
            ' * cannot drift from the driver.',
            ' */',
            '#include <stdio.h>',
            '#include <stddef.h>',
            '#include <stdint.h>',
            'typedef uint8_t  u8;',
            'typedef uint16_t __le16;',
            'typedef uint32_t __le32;',
            'typedef uint64_t __le64;',
            '', rec, '', hdr, '',
            '#define F(s, f) printf("%-26s %3zu %3zu\\n", #f, '
            'offsetof(struct s, f), sizeof(((struct s *)0)->f))',
            '', 'int main(void)', '{']

    for name, blob in (('dwc2_r1_rec', rec), ('dwc2_r1_dump_hdr', hdr)):
        body.append('\tprintf("struct %s  size=%%zu\\n", sizeof(struct %s));'
                    % (name, name))
        body.append('\tprintf("%-26s %3s %3s\\n", "field", "off", "sz");')
        for f in fields(blob):
            body.append('\tF(%s, %s);' % (name, f))
        body.append('\tprintf("\\n");')

    body += ['\treturn 0;', '}', '']
    open(a.out, 'w').write('\n'.join(body))
    print('%s: %d record fields, %d header fields'
          % (a.out, len(fields(rec)), len(fields(hdr))))


main()
